version: '3.7'
services:
  java-srv:
    build: java-srv
    ports:
      - 80:9000
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: az82/docker-derby
    ports:
      - 1527
    healthcheck:
      test: "pwd"