version: '3.7'
services:
  java-srv:
    build: java-srv
    ports:
      - 80:9000
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:alpine
    ports:
      - 5432
    healthcheck:
      test: "pwd"
    environment:
      - POSTGRES_DB=animal
      - POSTGRES_USER=maria
      - POSTGRES_HOST_AUTH_METHOD=trust